### PR TITLE
Add extra initialization commands for Quectel to handle incoming SMS & Calls

### PR DESCRIPTION
**Pull request by etnperlong**
Hi, I am very happy to see you contributed to this project. I am a user of EC20F (CN version, with voice module). I compiled your module on OpenWRT 22 with Asterisk 18 and found it works well :) and stably. But I think it still cannot handle incoming calls & SMS due to the lack of some initial commands and handlers for EC20.

I ported some codes to make these functions work last year and I hope it can help you. I think it can fix these issues:

- Handling incoming SMS & calls
- fix UCS-2 error when parsing some SMS with CJK characters

And I made an independent repo for compiling modules on OpenWRT with Asterisk 18, I hope it can help you as well.
https://github.com/etnperlong/openwrt-asterisk-chan-quectel

### CODE REVIEW

**Comment by IchthysMaranatha** [comment]
Hi, it already is set up for dsci. The setup for ring indication I think is a one time setup (and it's on by default for many models), so there's no need to add those to initialization commands, maybe a discussion for that might be created for more inputs. I'll look into this a little more at the end of the month when I plan to update call termination for simcom.

**Comment by IchthysMaranatha** [comment]
Hi, could you please use your EC20 with your modified code and then reboot the modem and use it with this unmodified code. Does that work? I wished to know if there are any additional volatile commands that are needed for the EC20 to work.

**Comment by etnperlong** [comment]
> 

Model: EC20F
Firmware: EC20CEFAGR06A15M4
Provider Name: CHINA MOBILE / CHN-UNICOM

Works: 
- Receive and send SMS (with CJK characters)
- Receive and make calls
- Inband DTMF

**Comment by IchthysMaranatha** [comment]
Ok, so only the UCS-2 patch is needed for Chinese characters sms. I'd put up a makefile in the openwrt folder that works with openwrt with a local feed. I did not prepare an auto-patch for the configure.ac though I've provided the patched configure.ac for compilation. Thanks, I'll do it the way you've done as is standard for openwrt compilation.

**Comment by IchthysMaranatha** [comment]
Have added chan_dongle ucs2 patch along with other updates, closing this

**Pull request closed without merging**
